name: build code, run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: test 1
      run: |
        echo "Owain Glyndwr" | ./name | tee output.txt
        grep "Welcome to C, Owain Glyndwr" output.txt
    - name: test 2
      run: |
        ./name < input1.txt | diff - output1.txt
