name: build code, run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: test with a name
      run: |
        echo "Owain Glyndwr" | ./name | tee output.txt | echo
        grep "Hello, Owain Glyndwr" output.txt
